defaults:
  - representation
  - override data: mc_bkg
  - _self_

data:
  active:
    - train
    - val
  image_key: pmaps


# encoder:
#   blocks_per_layer: 4
#   n_initial_filters: 32
#   downsampling: max_pooling

head:
  layers:
    - 256
    - 128
