defaults:
  - representation
  - override data: mc_tl208
  - _self_

data:
  active:
    - train
    - val
  image_key: pmaps

mode:
  optimizer:
    lr_schedule:
      peak_learning_rate: 0.1
# encoder:
#   blocks_per_layer: 4
#   n_initial_filters: 32
#   downsampling: max_pooling

head:
  layers:
    - 256
    - 128
