defaults:
  - supervised_classification
  - override encoder: resnet
  - override data: next-white-supervised
  - _self_

data:
  transform1: True
  transform2: False

encoder:
  n_output_filters: 64

head:
  layers: [2,]
    # - 128
    # - 128
    # - 64
    # - 2
