defaults:
  - supervised_classification
  - override data: mc_mk_tl208_cls
  - _self_

data:
  active:
    - train
    - val
  transform1: True
  transform2: False

head:
  layers: [128, 2]
    # - 128
    # - 128
    # - 64
    # - 2
