defaults:
  - supervised_classification
  - override encoder: convnet
  - override data: atpc_0nubb
  - _self_

data:
  active:
    - train
    - val
  transform1: False
  transform2: False

head:
  layers: [64,2,]
    # - 128
    # - 128
    # - 64
    # - 2
