defaults:
  - supervised_classification
  - override encoder: resnet
  - override data: mc_mk_tl208_cls
  - _self_

data:
  active:
    - train
    - val
  transform1: True
  transform2: False

encoder:
  n_output_filters: 2

head:
  layers: []
    # - 128
    # - 128
    # - 64
    # - 2
