defaults:
  - unsupervised_classification
  - override data: mc_mk_tl208_cls
  - _self_

data:
  active:
    - train
    - val
  transform1: False
  transform2: False

head:
  layers: [1]
    # - 128
    # - 128
    # - 64
    # - 2
