defaults:
  - detect_vertex
  # - override encoder: convnet
  - override data: next100_sim
  - _self_

data:
  active:
    - train
    - val
  transform1: False
  transform2: False

head:
  layers: 
    - 5 # [vertex present]