defaults:
  - detect_vertex
  - override encoder: convnet
  - override data: mc_mk_tl208_cls
  - _self_

data:
  active:
    - train
    - val
  transform1: False
  transform2: False

head:
  layers: 
    - 5 # [vertex present]